name: rifa_plus_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  google_fonts: ^6.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
